# Generated by Django 4.1.7 on 2023-05-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                default="123456", max_length=15, verbose_name="phone number"
            ),
            preserve_default=False,
        ),
    ]
