# Generated by Django 4.1.7 on 2023-05-18 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="phone_number",
        ),
    ]
