# Generated by Django 4.1.7 on 2023-05-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("king", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
