# Generated by Django 4.1.7 on 2023-05-15 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("king", "0003_alter_product_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-created_at"]},
        ),
    ]
