# Generated by Django 4.1.7 on 2023-05-20 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("king", "0004_alter_product_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Female",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Male",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "girles",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="king.female"
                    ),
                ),
            ],
        ),
    ]
