# Generated by Django 4.1.7 on 2023-05-20 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("king", "0005_female_male"),
    ]

    operations = [
        migrations.CreateModel(
            name="Relationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "female",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="king.female"
                    ),
                ),
                (
                    "male",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="king.male"
                    ),
                ),
            ],
        ),
    ]
