# Generated by Django 4.1.7 on 2023-05-20 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("king", "0006_relationship"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="male",
            name="girles",
        ),
        migrations.RemoveField(
            model_name="relationship",
            name="female",
        ),
        migrations.RemoveField(
            model_name="relationship",
            name="male",
        ),
        migrations.DeleteModel(
            name="Female",
        ),
        migrations.DeleteModel(
            name="Male",
        ),
        migrations.DeleteModel(
            name="Relationship",
        ),
    ]
