# Generated by Django 4.1.7 on 2023-05-21 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("king", "0008_female_show_male_female"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="female",
            name="men",
        ),
        migrations.AlterField(
            model_name="female",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="male",
            name="girles",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="king.female"
            ),
        ),
        migrations.DeleteModel(
            name="Female_show",
        ),
    ]
