# Generated by Django 4.1.7 on 2023-05-21 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("king", "0011_female_male"),
    ]

    operations = [
        migrations.AlterField(
            model_name="male",
            name="girles",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to="king.female"
            ),
        ),
    ]
